### ISSUE TITLE
Exception in channel set command

### ISSUE THREAD

**Issue by RainbowDashLabs** [RainbowDashLabs/reputation-bot#123]
Unknown interaction.
at de.chojo.repbot.commands.Channel.set(Channel.java:248)
```
[12:32:46][ERR][  ReputationBot] Unhandled exception occured: net.dv8tion.jda.api.exceptions.ErrorResponseException: 10062: Unknown interaction
at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:117)
at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:270)
at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackActionImpl.handleResponse(InteractionCallbackActionImpl.java:85)
at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:259)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:238)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:142)
at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:125)
at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:478)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71)
at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)
at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackActionImpl.queue(InteractionCallbackActionImpl.java:113)
at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
at de.chojo.repbot.commands.Channel.set(Channel.java:248)
at de.chojo.repbot.commands.Channel.onSlashCommand(Channel.java:86)
at de.chojo.jdautil.command.dispatching.CommandHub.onSlashCommand(CommandHub.java:120)
at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:463)
at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
at net.dv8tion.jda.internal.hooks.EventManagerProxy.lambda$handle$0(EventManagerProxy.java:68)
... 3 more```

**Comment by Taucher2003** [comment]
This has a commit.
Is this done and can be closed?

**Comment by RainbowDashLabs** [comment]
It will be closed on merging. Its not merged yet and therefore not done.
